# Generated by Django 5.0.6 on 2026-07-30 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Tavsif (ixtiyoriy)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Biz haqimizda rasm',
                'verbose_name_plural': 'Biz haqimizda rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Ost sarlavha')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Rasm')),
                ('button_text', models.CharField(default="Mahsulotlarni ko'rish", max_length=50, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='/products/', max_length=200, verbose_name='Tugma havolasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqamini to'g'ri formatda kiriting. Masalan: +998901234567", regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')], verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
            ],
            options={
                'verbose_name': 'Kontakt xabari',
                'verbose_name_plural': 'Kontakt xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SpongeFactory', max_length=100, verbose_name='Sayt nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name="Qo'shimcha telefon")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=150, verbose_name='Telegram (havola yoki @username)')),
                ('instagram', models.CharField(blank=True, max_length=150, verbose_name='Instagram (havola)')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('google_map_embed', models.TextField(blank=True, help_text="Google Maps dan 'Share > Embed a map' orqali olingan <iframe> kodini shu yerga joylashtiring.", verbose_name='Google Map iframe kodi')),
                ('about_short', models.TextField(blank=True, verbose_name="Bosh sahifadagi qisqa ma'lumot")),
                ('about_text', models.TextField(blank=True, verbose_name="Biz haqimizda — to'liq matn")),
                ('production_process', models.TextField(blank=True, verbose_name='Ishlab chiqarish jarayoni matni')),
                ('why_choose_us', models.TextField(blank=True, verbose_name='Nima uchun bizni tanlashadi')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Sayt uchun umumiy meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Sayt uchun umumiy meta description')),
                ('footer_copyright', models.CharField(default='© 2026 SpongeFactory. Barcha huquqlar himoyalangan.', max_length=200, verbose_name='Footer copyright matni')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Narxi (so'm)")),
                ('short_description', models.CharField(max_length=255, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(blank=True, verbose_name="To'liq tavsif")),
                ('main_image', models.ImageField(upload_to='products/', verbose_name='Asosiy rasm')),
                ('is_featured', models.BooleanField(default=False, help_text="Bosh sahifada ko'rsatiladi", verbose_name='Mashhur mahsulot')),
                ('is_active', models.BooleanField(default=True, verbose_name="Faol (saytda ko'rinadi)")),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni (dona/quti)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta title (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmi',
                'verbose_name_plural': 'Mahsulot rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism familya')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqamini to'g'ri formatda kiriting. Masalan: +998901234567", regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')], verbose_name='Telefon')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Korxona nomi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', "Ko'rib chiqilmoqda"), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_orders', to='shop.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Optom buyurtma',
                'verbose_name_plural': 'Optom buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
